[package]
name = "rigel"
version = "1.0.0"
authors = []

[addresses]
rigel = "1e439e8919738ac6a154ba5a0fbca190945d061e66bb2be331c2a61996f09101"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.ThalaLSD]
local = "./ThalaLSD"

[dependencies.amnis]
local = "./amnis"

[dev-dependencies]

