[package]
name = "rigel"
version = "1.0.0"
authors = []

[addresses]
rigel = "0x123"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.Rigel]
local = ".."

[dev-dependencies]

