[package]
name = "rigel"
version = "1.0.0"
authors = []

[addresses]
rigel = "0xaccfff672e2d7fd753d675a891e3110b1c4977eb00156a9bf675ca8d6ed2fe22"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.ThalaLSD]
local = "./ThalaLSD"

[dev-dependencies]

