[package]
name = "rigel"
version = "1.0.0"
authors = []

[addresses]
rigel = "0x3bb1341760719b5ade7d9b32b3deb3e5dc1a4f1045ea4eadc8ba169a22224049"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

